name = "douren-backend"
node_compat = true
compatibility_date = "2024-08-30"
[env.staging]
vars = { DEV_ENV = "stg" }
routes = [
    { pattern = "stg.api.douren.net", custom_domain = true }
]
[env.production]
vars = { DEV_ENV = "prod" }
routes = [
    { pattern = "api.douren.net", custom_domain = true }
]
[triggers]
crons = ["0 0 * * *"]
