export interface OldFF {
  author_name: string | null
          baha_link: string | null
          baha_name: string | null
          DAY01_location: string | null
          DAY02_location: string | null
          DAY03_location: string | null
          DM: string | null
          doujin_name: string | null
          Facebook_link: string | null
          Facebook_name: string | null
          id: string
          Instagram_link: string | null
          Instagram_name: string | null
          other_website: string | null
          photo: string | null
          PIXIV_link: string | null
          PIXIV_name: string | null
          plurk_link: string | null
          plurk_name: string | null
          store_link: string | null
          tag: string | null
          Twitch_link: string | null
          Twitch_name: string | null
          Twitter_link: string | null
          Twitter_name: string | null
          YouTube_link: string | null
          YouTube_name: string | null
}
