name = "douren-frontend"
pages_build_output_dir = "./dist"
[env.preview]
routes = [
    { pattern = "stg.douren.net", custom_domain = true }
]

[env.production]
routes = [
    { pattern = "douren.net", custom_domain = true }
]
