version: "1.1"
name: tRPC
tests:
  example:
    steps:
      - name: Query
        http:
          url: http://localhost:2022/trpc
          trpc:
            query:
              greet: Mish
          check:
            status: /^20/