export interface FF {
  Author: string | null;
  Baha_link: string | null;
  Baha_name: string | null;
  Booth_name: string | null;
  DAY01_location: string | null;
  DAY02_location: string | null;
  DAY03_location: string | null;
  DM: string | undefined;
  Facebook_link: string | null;
  Facebook_name: string | null;
  uuid: string;
  Instagram_link: string | null;
  Instagram_name: string | null;
  Official_link: string | null;
  Photo: string | undefined;
  Pixiv_link: string | null;
  Pixiv_name: string | null;
  Plurk_link: string | null;
  Plurk_name: string | null;
  Store_link: string | null;
  Tag: string | null;
  Twitch_link: string | null;
  Twitch_name: string | null;
  Twitter_link: string | null;
  Twitter_name: string | null;
  Youtube_link: string | null;
  Youtube_name: string | null;
}
