/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionIndexRouteImport } from './routes/collection/index'
import { Route as ArtistIndexRouteImport } from './routes/artist/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as EventEventNameRouteImport } from './routes/event/$eventName'
import { Route as ArtistArtistIdIndexRouteImport } from './routes/artist/$artistId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/collection/',
  path: '/collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIndexRoute = ArtistIndexRouteImport.update({
  id: '/artist/',
  path: '/artist/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventNameRoute = EventEventNameRouteImport.update({
  id: '/event/$eventName',
  path: '/event/$eventName',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistArtistIdIndexRoute = ArtistArtistIdIndexRouteImport.update({
  id: '/artist/$artistId/',
  path: '/artist/$artistId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/event/$eventName': typeof EventEventNameRoute
  '/about': typeof AboutIndexRoute
  '/artist': typeof ArtistIndexRoute
  '/collection': typeof CollectionIndexRoute
  '/artist/$artistId': typeof ArtistArtistIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/event/$eventName': typeof EventEventNameRoute
  '/about': typeof AboutIndexRoute
  '/artist': typeof ArtistIndexRoute
  '/collection': typeof CollectionIndexRoute
  '/artist/$artistId': typeof ArtistArtistIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/event/$eventName': typeof EventEventNameRoute
  '/about/': typeof AboutIndexRoute
  '/artist/': typeof ArtistIndexRoute
  '/collection/': typeof CollectionIndexRoute
  '/artist/$artistId/': typeof ArtistArtistIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/event/$eventName'
    | '/about'
    | '/artist'
    | '/collection'
    | '/artist/$artistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/event/$eventName'
    | '/about'
    | '/artist'
    | '/collection'
    | '/artist/$artistId'
  id:
    | '__root__'
    | '/'
    | '/event/$eventName'
    | '/about/'
    | '/artist/'
    | '/collection/'
    | '/artist/$artistId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventEventNameRoute: typeof EventEventNameRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ArtistIndexRoute: typeof ArtistIndexRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
  ArtistArtistIdIndexRoute: typeof ArtistArtistIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/': {
      id: '/artist/'
      path: '/artist'
      fullPath: '/artist'
      preLoaderRoute: typeof ArtistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventName': {
      id: '/event/$eventName'
      path: '/event/$eventName'
      fullPath: '/event/$eventName'
      preLoaderRoute: typeof EventEventNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$artistId/': {
      id: '/artist/$artistId/'
      path: '/artist/$artistId'
      fullPath: '/artist/$artistId'
      preLoaderRoute: typeof ArtistArtistIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventEventNameRoute: EventEventNameRoute,
  AboutIndexRoute: AboutIndexRoute,
  ArtistIndexRoute: ArtistIndexRoute,
  CollectionIndexRoute: CollectionIndexRoute,
  ArtistArtistIdIndexRoute: ArtistArtistIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
