// This file is auto-generated by scripts/generate-env-binding.js
// Do not edit it directly. Run the script to regenerate.

export interface ENV_BINDING {
  CLOUDFLARE_ACCOUNT_ID: string;
  CLOUDFLARE_API_KEY: string;
  CLOUDFLARE_IMAGE_AUTH_TOKEN: string;
  CLOUDFLARE_IMAGE_ENDPOINT: string;
  CLOUDFLARE_IMAGE_TOKEN: string;
  DATABASE_URL: string;
  DEV_ENV: string;
  TURBO_TOKEN: string;
  VITE_BACKEND_URL: string;
  VITE_BASIC_AUTH_TOKEN: string;
  VITE_IMAGE_URL: string;
  VITE_IMAGE_URL_TOKEN: string;
}

// Legacy exports for backward compatibility (will be removed in future versions)
export type BACKEND_BINDING = ENV_BINDING;
export type FRONTEND_BINDING = ENV_BINDING;
export type PACKAGE_BINDING = ENV_BINDING;
