// This file is auto-generated by scripts/generate-env-binding.js
// Do not edit it directly. Run the script to regenerate.
// Note: AXIOM_TOKEN and AXIOM_DATASET must be added to Infisical for regeneration

export interface ENV_BINDING {
  AXIOM_DATASET: string;
  AXIOM_TOKEN: string;
  BETTER_AUTH_SECRET: string;
  BETTER_AUTH_URL: string;
  CLOUDFLARE_ACCOUNT_ID: string;
  CLOUDFLARE_API_KEY: string;
  CLOUDFLARE_IMAGE_AUTH_TOKEN: string;
  CLOUDFLARE_IMAGE_ENDPOINT: string;
  CLOUDFLARE_IMAGE_TOKEN: string;
  CMS_FRONTEND_URL: string;
  DATABASE_URL: string;
  DEV_ENV: string;
  TURBO_TOKEN: string;
  VITE_ADMIN_AUTH_TOKEN: string;
  VITE_API_URL: string;
  VITE_BACKEND_URL: string;
  VITE_BASIC_AUTH_TOKEN: string;
  VITE_CLERK_PUBLISHABLE_KEY: string;
  VITE_DEV_ENV: string;
  VITE_IMAGE_URL: string;
  VITE_IMAGE_URL_TOKEN: string;
  ZERO_REPLICA_FILE: string;
  ZERO_UPSTREAM_DB: string;
}

// Legacy exports for backward compatibility (will be removed in future versions)
export type BACKEND_BINDING = ENV_BINDING;
export type FRONTEND_BINDING = ENV_BINDING;
export type PACKAGE_BINDING = ENV_BINDING;
