name = "douren-image-api"
compatibility_date = "2024-08-12"
node_compat = true
[dev]
port = 2001

[env.staging.observability]
enabled = true

[env.production.observability]
enabled = true

[env.staging]
vars = { DEV_ENV = "stg" }
routes = [
    { pattern = "stg.img.api.douren.net", custom_domain = true }
]
[env.production]
vars = { DEV_ENV = "prod" }
routes = [
    { pattern = "img.api.douren.net", custom_domain = true }
]
