name: Douren Image Backend Deploy Pipeline

on:
  push:
    branches:
      - "main"

jobs:
  be-img-prod-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Production Deploy
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Get Env Variable
        env:
          dotenv: ${{secrets.DOTENV_ME}}
        run: npx dotenv-vault pull production --dotenvMe=$dotenv -y && mv .env.production .env &&make copy-env

      - name: Build Packages
        run: npm run pkg

      - name: Build Library
        run: npm run lib

      - name: Deploy Backend
        env:
          CF_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_KEY }}
        run: |
          cd be/douren-image-api
          WRANGLER_VARS=""
              while IFS= read -r line || [[ -n "$line" ]]; do
              if [[ ! $line =~ ^\s*# ]] && [[ -n "$line" ]] && [[ ! $line =~ ^DEV_ENV= ]]; then
              key=$(echo "$line" | cut -d '=' -f 1 | xargs)
              value=$(echo "$line" | cut -d '=' -f 2- | tr -d '\r' | xargs)
              WRANGLER_VARS+="--var ${key}=\"${value}\" "
              fi
              done < .env 
          echo "Debug: WRANGLER_VARS=$WRANGLER_VARS" 
          npm run deploy -- $WRANGLER_VARS --env production 
